# Default values for concierge-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: concierge-app
namespace: helm-test

# OpenShift objects
route: false

# if false use a kube deployment instead
deploymentConfig: false
replicas:
  min: 2
  max: 6
image_repository: quay.io
image_name: concierge-app
image_namespace: quarkus-dev
image_version: latest

buildconfig: 
  enabled: true
  runtime: java
  runtimeVersion: openjdk-17-ubi8
  git:
    uri: 'https://github.com/firefighters-sre/concierge-app'

# use the image specified above as tag (else tag overridden in pipeline say)
istag:
  enabled: true

hpa:
  enabled: false
  cpuTarget: 200m
  memTarget: 300Mi

pdb:
  enabled: false

prometheus:
  rules:
    enabled: false
    severity: warning
  servicemonitor:
    enabled: false

# service mesh
istio:
  enabled: false
  mtls: true
  domain: apps.hivec.sandbox209.opentlc.com


