{{- if .Values.prometheus.rules.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: concierge-app-alerts
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: concierge-app.rules
    rules:
    - alert: ConciergeAppNotAvailable
      annotations:
        message: 'Concierge App in namespace {{ .Values.namespace  }} is not available for the last 1 minutes.'
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Values.namespace  }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="concierge-app",namespace="{{ .Values.namespace }}"})) == 0
      for: 1m
      labels:
        severity: {{ .Values.prometheus.rules.severity | default "critical" }}
{{ end }}